author: John Fairhurst
author_url: https://toomanyladybirds.com/
module: TMLPersistentContainer
copyright: © 2017 John Fairhurst. All rights reserved.
readme: README.md
github_url: https://github.com/johnfairh/TMLPersistentContainer
documentation: SourceDocs/Usage.md
