author: John Fairhurst
author_url: https://toomanyladybirds.com/
module: TMLPersistentContainer
copyright: Distributed under the ISC license.  Maintained by John Fairhurst.
readme: README.md
github_url: https://github.com/johnfairh/TMLPersistentContainer
documentation: SourceDocs/*md
