language: objective-c
osx_image: xcode8.3
script:
    - xcodebuild clean build -sdk iphonesimulator -project TMLPersistentContainer.xcodeproj -scheme TMLPersistentContainer-iOS CODE_SIGNING_REQUIRED=NO
    - xcodebuild test -sdk iphonesimulator -project TMLPersistentContainer.xcodeproj -scheme TMLPersistentContainer-iOS CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 5s'
after_success:
    - bash <(curl -s https://codecov.io/bash)
